# Figure 3D/S6/S7 
# They involve an extremely large space and consumes computational time. 
# Corresponding files in the ./Simualtion/ folder, and it is recommended 
# to run in parallel mode.

# Example:
# Each gene repeat 10 times >>>
# Rscript	exe_LocalFrustrations_AllGene_OEKD_SetSM_Parallel.R	[randome seed] [Gene name] [string] 
# Then combine them >>>
# Rscript	exe_LocalFrustrations_AllGene_OEKD_SetSM_Parallel.R	[Gene name]
# Can return series figures as 3D/S6/S7
# !WARNING: Recommend change the directory "/dev/shm/" as your appropriate one to avoid memory explosion
# !WARNING: for parallel executing, you should change the relative address to an absolute one.
# !WARNING: original landscapes used in Fig3D/S7 are same, relevant data can be prepared via "./Simualtion/exe_OriScatter.R"

# Load benchmark data.
adjmat=readRDS("./Data_Used/AdjacentMatrix.Matrix.rds");
source("./Auxiliary_Functions_for_Figure/aux_ggplot2Theme.R");
MEFs=readRDS("./Intermediate_Result/ExtremeCase_FourClusters.rds");
MEFs=MEFs$sm;
# "All_Result_onlyPou5f1.rds" can be generated by ./Simulation/*Pou5f1_*.R as above notes.
# This is an exmple for showing the process.
AllResult=readRDS("/dev/shm/All_Result_onlyPou5f1.rds");# This may be slow, please wait.

# Extract appropriate states, paths, or coordinates
num_id_high=c(1:1000000)[(AllResult$New_PS-AllResult$Ori_PS)>6];
#num_id_lows=c(1:1000000)[(AllResult$New_PS-AllResult$Ori_PS)<6];
delta_gene=AllResult$NewState[num_id_high,]-MEFs[num_id_high,];
delta_gene=colSums(abs(delta_gene))/nrow(delta_gene);

# Set spin-like MEF-matrix and adjusted adjacent matrix.
adjmat_0=adjmat;
diag(adjmat_0)=0;# Remove the self-regulatory patterns.
mef_spin=MEFs[num_id_high,];
mef_spin[mef_spin<1]=-1;
# Calculate each gene's local-fru of each cell.
loc.fru.ori=matrix(NA,nrow(mef_spin),ncol(adjmat_0));
colnames(loc.fru.ori)=colnames(adjmat_0);
for(ii in c(1:ncol(mef_spin))){
  loc.fru.ori[,ii]=-(mef_spin%*%adjmat_0[ii,])*mef_spin[,ii];
}
# Calculate each gene's local-fru of each cell. (Have perturbation)
mef_spin[,"Pou5f1"]=1;# Exist external factor!
loc.fru.per=matrix(NA,nrow(mef_spin),ncol(adjmat_0));
colnames(loc.fru.per)=colnames(adjmat_0);
for(ii in c(1:ncol(mef_spin))){
  loc.fru.per[,ii]=-(mef_spin%*%adjmat_0[ii,])*mef_spin[,ii];
}

# Obtain valid varied genes.
loc.fru.del=loc.fru.per-loc.fru.ori;
id_delta_av=colMeans(loc.fru.del[,delta_gene>0]);
id_delta_sd=apply(loc.fru.del[,delta_gene>0],2,sd);

# Prepare dataframe of figure.
non0VarGene=loc.fru.ori[,delta_gene>0];
OriLocalFru=data.frame(
  x=delta_gene[delta_gene>0],# Non-zero genes, changign ratios
  y=colMeans(non0VarGene),# Mean of each gene's local frustration
  er=apply(non0VarGene,2,sd),# Standard Deviation of each gene's local frustration
  t=colMeans(mef_spin[,delta_gene>0]));# Mean of initial values of genes, [-1,+1]
rownames(OriLocalFru)=colnames(mef_spin)[delta_gene>0];

# Monotone decreasing trend of local frustration vs av.changed ratio.
figs=ggplot(OriLocalFru[abs(id_delta_av)>1e-5&abs(id_delta_sd)>1e-5&rownames(OriLocalFru)!="Pou5f1",],
  aes(x=x,y=y))+
  geom_errorbar(aes(x=x,ymin=y-er,ymax=y+er),linewidth=1.0,alpha=0.2)+
  geom_point(aes(fill=t),col="#000000",shape=21,size=2,stroke=0.5)+
  scale_fill_gradient2(low="#8359B5",mid="white",high="#008844",midpoint=0)+
  labs(x="Av. Changed Ratio",y="Local Frustration");
figs=Plot_ThemeConfiguration(figs)+theme(legend.position = c(0.26,0.24),aspect.ratio=1.0,);
ggsave(filename="./Figure_OriginalVersion/LocalFrustration_vs_AvChangedGene_valid.pdf",
  figs, width=5.5, height=4.0, units="in");
# Show the negative correalation:
# models=lm(y~x, data=OriLocalFru[abs(id_delta_av)>1e-5&abs(id_delta_sd)>1e-5&rownames(OriLocalFru)!="Pou5f1",])
# summary(models)

# Monotone decreasing trend of local frustration vs av.changed ratio (all nodes)
figs=ggplot(OriLocalFru,aes(x=x,y=y))+
  geom_errorbar(aes(x=x,ymin=y-er,ymax=y+er),linewidth=1.0,alpha=0.2)+
  geom_point(aes(fill=t),col="#000000",shape=21,size=2,stroke=0.5)+
  scale_fill_gradient2(low="#8359B5",mid="white",high="#008844",midpoint=0)+
  labs(x="Av. Changed Ratio",y="Local Frustration");
figs=Plot_ThemeConfiguration(figs)+theme(legend.position = c(0.26,0.24),aspect.ratio=1.0,);
ggsave(filename="./Figure_OriginalVersion/LocalFrustration_vs_AvChangedGene_all.pdf",
  figs, width=5.5, height=4.0, units="in");

rm(list=ls());gc();
# Code is over.